include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v16.0.0-beta.10

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "true"
  AUTO_DEVOPS_PRODUCTION_AUTO: "/^v[1-9]+\\.[0-9]+\\.[0-9]+$/"

#

# NOTE(douglasduteil): use custom build job
# The website it statically built with Nextjs
# Here we manually run `yarn next export` and reuse the `out` dir in Dockerfile
Build:
  extends:
    - .autodevops_build
  variables:
    VERSION: ${CI_COMMIT_SHORT_SHA}
  script:
    - yarn next build
    - yarn next export
  artifacts:
    expire_in: 1 day
    paths:
      - out
