include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v9.1.1

variables:
  PROJECT: "www"
  # NOTE(douglasduteil): explicit project path
  # As GitLab is setting CI_PROJECT_PATH to SocialGouv/socialgouv-github-io
  PROJECT_PATH: "SocialGouv/socialgouv.github.io" 
  HELM_CHART_VERSION: "3.0.1"
  VALUES_FILE: ./.k8s/app.values.yml
